name: tumblr
description: Flutter onboarding project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: 5.2.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^10.1.0
  injectable: ^2.3.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lint: 2.1.2
  path_provider: ^2.0.8
  shake_flutter: ^16.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.4.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true
